eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  ignoredServices: "*"
  routes:
    city:
      path: /city-service/**
      serviceId: CITY-DOMAIN
      stripPrefix: true
    itinerary:
      path: /itinerary-service/**
      serviceId: ITINERARY-SERVICE
      stripPrefix: true